parallel-jobs = 2

[default]
patcher-args = []
included-patches = []
excluded-patches = []

# ==================== YouTube RVX (anddea) ====================
[YouTube-RVX]
app-name = "YouTube RVX"
package-name = "org.videolan.vlc"          # ← TWOJA ZMIANA (spoof VLC)
enabled = true
build-mode = "both"
version = "auto"

patches-source = "anddea/revanced-patches"
cli-source = "MorpheApp/morphe-cli"
integrations-source = ""

apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

# ==================== X / Twitter Piko ====================
[X-Piko]
app-name = "X (Piko)"                       # zostaje X, nie Twitter
package-name = "com.twitter.android"
enabled = true
build-mode = "apk"
version = "auto"

patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-cli"
integrations-source = ""

included-patches = ["Dynamic color"]        # ← włącza Material You
excluded-patches = ["Bring back twitter"]   # ← blokuje zmianę na Twitter

apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
archive-dlurl = "https://archive.org/download/geologically/apks/com.twitter.android"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
dpi = "120-640dpi"