parallel-jobs = 1
remove-rv-integrations-checks = false
debug = true

[default]
cli-source = "inotia00/revanced-cli"
cli-args = []

# ==================== YouTube RVX (anddea) ====================
[youtube-anddea]
app-name = "com.google.android.youtube"
enabled = true
build-mode = "apk"
version = "auto"
arch = "arm64-v8a"
include-stock = false

cli-source = "inotia00/revanced-cli"
patches-source = "anddea/revanced-patches"
integrations-source = ""

patcher-args = ""

archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

# ==================== X / Twitter (Piko) ====================
[twitter-piko]
app-name = "com.twitter.android"
enabled = true
build-mode = "apk"
version = "auto"
arch = "arm64-v8a"
include-stock = false

cli-source = "inotia00/revanced-cli"
patches-source = "crimera/piko"
integrations-source = ""

patcher-args = "-e 'Bring back twitter'"

archive-dlurl = "https://archive.org/download/geologically/apks/com.twitter.android"
dpi = "120-640dpi"